import type { SessionMeta } from "@/lib/ipc"
import { getSessionTitle } from "@/lib/sessionTitles"

type SessionTitleMeta = Pick<SessionMeta, "id" | "ai_title" | "first_user_text">

const LOCAL_COMMAND_CAVEAT_PREFIX =
  "Caveat: The messages below were generated by the user while running local commands.".toLowerCase()

export function isInternalCommandText(text: string): boolean {
  const trimmed = text.trimStart()
  const lower = trimmed.toLowerCase()
  if (lower.startsWith(LOCAL_COMMAND_CAVEAT_PREFIX)) return true
  const opening = trimmed.match(
    /^<(command-name|command-message|command-args|local-command-[a-z0-9-]+|bash-(?:input|stdout|stderr)|system-reminder|task-notification|local-command-caveat)>/i
  )
  if (!opening) return false
  return lower.includes(`</${opening[1].toLowerCase()}>`)
}

export function cleanSessionTitleText(
  text: string | null | undefined,
  maxChars = 120
): string | null {
  const trimmed = stripInternalTextSections(text).trim()
  if (!trimmed || isInternalCommandText(trimmed)) return null
  return Array.from(trimmed.replace(/\s+/g, " ")).slice(0, maxChars).join("")
}

function stripInternalTextSections(text: string | null | undefined): string {
  if (!text) return ""
  return text
    .replace(/<system-reminder>[\s\S]*?<\/system-reminder>/gi, "")
    .replace(/<local-command-caveat>[\s\S]*?<\/local-command-caveat>/gi, "")
    .replace(/<task-notification>[\s\S]*?<\/task-notification>/gi, "")
}

export function sessionGeneratedTitle(session: SessionTitleMeta): string | null {
  return (
    cleanSessionTitleText(session.ai_title) ||
    cleanSessionTitleText(session.first_user_text)
  )
}

export function sessionDisplayTitle(session: SessionTitleMeta): string {
  return (
    getSessionTitle(session.id) ||
    sessionGeneratedTitle(session) ||
    session.id.slice(0, 8)
  )
}
